export const CURRENCIES = [
  { value: "USD", label: "US Dollar", flag: "https://flagcdn.com/us.svg" },
  { value: "EUR", label: "Euro", flag: "https://flagcdn.com/eu.svg" },
  { value: "JPY", label: "Japanese Yen", flag: "https://flagcdn.com/jp.svg" },
  { value: "GBP", label: "British Pound", flag: "https://flagcdn.com/gb.svg" },
  {
    value: "AUD",
    label: "Australian Dollar",
    flag: "https://flagcdn.com/au.svg",
  },
  {
    value: "CAD",
    label: "Canadian Dollar",
    flag: "https://flagcdn.com/ca.svg",
  },
  { value: "CHF", label: "Swiss Franc", flag: "https://flagcdn.com/ch.svg" },
  { value: "CNY", label: "Chinese Yuan", flag: "https://flagcdn.com/cn.svg" },
  { value: "RUB", label: "Russian Ruble", flag: "https://flagcdn.com/ru.svg" },
  {
    value: "UZS",
    label: "Uzbekistani Som",
    flag: "https://flagcdn.com/uz.svg",
  },
  {
    value: "KZT",
    label: "Kazakhstani Tenge",
    flag: "https://flagcdn.com/kz.svg",
  },
  {
    value: "KGS",
    label: "Kyrgyzstani Som",
    flag: "https://flagcdn.com/kg.svg",
  },
  { value: "INR", label: "Indian Rupee", flag: "https://flagcdn.com/in.svg" },
  { value: "BRL", label: "Brazilian Real", flag: "https://flagcdn.com/br.svg" },
  {
    value: "ZAR",
    label: "South African Rand",
    flag: "https://flagcdn.com/za.svg",
  },
  { value: "MXN", label: "Mexican Peso", flag: "https://flagcdn.com/mx.svg" },
  {
    value: "KRW",
    label: "South Korean Won",
    flag: "https://flagcdn.com/kr.svg",
  },
  {
    value: "SGD",
    label: "Singapore Dollar",
    flag: "https://flagcdn.com/sg.svg",
  },
  { value: "TRY", label: "Turkish Lira", flag: "https://flagcdn.com/tr.svg" },
  {
    value: "NZD",
    label: "New Zealand Dollar",
    flag: "https://flagcdn.com/nz.svg",
  },
  { value: "SEK", label: "Swedish Krona", flag: "https://flagcdn.com/se.svg" },
  {
    value: "NOK",
    label: "Norwegian Krone",
    flag: "https://flagcdn.com/no.svg",
  },
  { value: "PLN", label: "Polish Zloty", flag: "https://flagcdn.com/pl.svg" },
  { value: "ARS", label: "Argentine Peso", flag: "https://flagcdn.com/ar.svg" },
  { value: "AED", label: "UAE Dirham", flag: "https://flagcdn.com/ae.svg" },
  { value: "SAR", label: "Saudi Riyal", flag: "https://flagcdn.com/sa.svg" },
  { value: "THB", label: "Thai Baht", flag: "https://flagcdn.com/th.svg" },
  {
    value: "VND",
    label: "Vietnamese Dong",
    flag: "https://flagcdn.com/vn.svg",
  },
  {
    value: "MYR",
    label: "Malaysian Ringgit",
    flag: "https://flagcdn.com/my.svg",
  },
  {
    value: "IDR",
    label: "Indonesian Rupiah",
    flag: "https://flagcdn.com/id.svg",
  },
  { value: "EGP", label: "Egyptian Pound", flag: "https://flagcdn.com/eg.svg" },
  {
    value: "HKD",
    label: "Hong Kong Dollar",
    flag: "https://flagcdn.com/hk.svg",
  },
  { value: "DKK", label: "Danish Krone", flag: "https://flagcdn.com/dk.svg" },
  { value: "CLP", label: "Chilean Peso", flag: "https://flagcdn.com/cl.svg" },
  {
    value: "PKR",
    label: "Pakistani Rupee",
    flag: "https://flagcdn.com/pk.svg",
  },
  { value: "QAR", label: "Qatari Riyal", flag: "https://flagcdn.com/qa.svg" },
  {
    value: "BDT",
    label: "Bangladeshi Taka",
    flag: "https://flagcdn.com/bd.svg",
  },
  {
    value: "LKR",
    label: "Sri Lankan Rupee",
    flag: "https://flagcdn.com/lk.svg",
  },
  { value: "COP", label: "Colombian Peso", flag: "https://flagcdn.com/co.svg" },
  { value: "NGN", label: "Nigerian Naira", flag: "https://flagcdn.com/ng.svg" },
  {
    value: "UAH",
    label: "Ukrainian Hryvnia",
    flag: "https://flagcdn.com/ua.svg",
  },
  {
    value: "MAD",
    label: "Moroccan Dirham",
    flag: "https://flagcdn.com/ma.svg",
  },
  { value: "ILS", label: "Israeli Shekel", flag: "https://flagcdn.com/il.svg" },
  { value: "DZD", label: "Algerian Dinar", flag: "https://flagcdn.com/dz.svg" },
  { value: "TND", label: "Tunisian Dinar", flag: "https://flagcdn.com/tn.svg" },
  {
    value: "JOD",
    label: "Jordanian Dinar",
    flag: "https://flagcdn.com/jo.svg",
  },
  {
    value: "TWD",
    label: "New Taiwan Dollar",
    flag: "https://flagcdn.com/tw.svg",
  },
  {
    value: "HUF",
    label: "Hungarian Forint",
    flag: "https://flagcdn.com/hu.svg",
  },
  { value: "CZK", label: "Czech Koruna", flag: "https://flagcdn.com/cz.svg" },
];
